### ISSUE TITLE
Mongoose version

### ISSUE THREAD

**Issue by muqsith** [krakenjs/kraken-example-with-shoppingcart#23]
Please change the mongoose version from "~3.8.8" to "^4.6.6". I get following error on Ubuntu 16.04 with 3.8.8 during npm install
`
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/muqsith/Development/node/kraken-example-with-shoppingcart/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
kerberos.target.mk:92: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: Leaving directory '/home/muqsith/Development/node/kraken-example-with-shoppingcart/node_modules/kerberos/build'

> bson@0.2.22 install /home/muqsith/Development/node/kraken-example-with-shoppingcart/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/muqsith/Development/node/kraken-example-with-shoppingcart/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
bson.target.mk:86: recipe for target 'Release/obj.target/bson/ext/bson.o' failed
`
and the following during npm start
`{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/muqsith/Development/node/kraken-example-with-shoppingcart/node_modules/mongodb/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/muqsith/Development/node/kraken-example-with-shoppingcart/node_modules/mongodb/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
`

But when I use version "^4.6.6", both the error dissapear.

Also there is a typo in the file name ./public/views/Products.jsx , it should be "products.jsx" (P in lower case).

**Comment by grawk** [comment]
Really we should dump mongo out of this example. It's a silly overhead given this is an example about kraken. But will address this one way or the other. Thanks for reporting.

**Comment by tlivings** [comment]
IMO just replace with levelDB.

**Comment by tlivings** [comment]
Or in memory.

**Comment by grawk** [comment]
yeah @subeeshcbabu used `lokijs` in a recent example:
https://github.com/subeeshcbabu/krakenjs-angular2/blob/master/inmemorydb/index.js#L6

We should do the same.

**Comment by grawk** [comment]
using lokijs to simplify
