### ISSUE TITLE
Unable to use Kraken

### ISSUE THREAD

**Issue by abhinavralhan** [krakenjs/kraken-example-with-shoppingcart#27]
So, I wanted to see how Kraken works out and tried running the same. I followed all the instructions yet was unable. The error is show below. I couldn't figure out the error/warning shown below. If someone could explain how to get Kraken working I'd be glad. Thanks in advance

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.0.3
3 info using node@v8.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kraken-example-with-shoppingcart@0.1.0~prestart: kraken-example-with-shoppingcart@0.1.0
6 silly lifecycle kraken-example-with-shoppingcart@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle kraken-example-with-shoppingcart@0.1.0~start: kraken-example-with-shoppingcart@0.1.0
8 verbose lifecycle kraken-example-with-shoppingcart@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle kraken-example-with-shoppingcart@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/abhinavralhan/kraken-example-with-shoppingcart/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle kraken-example-with-shoppingcart@0.1.0~start: CWD: /home/abhinavralhan/kraken-example-with-shoppingcart
11 silly lifecycle kraken-example-with-shoppingcart@0.1.0~start: Args: [ '-c', 'grunt build && node index.js' ]
12 info lifecycle kraken-example-with-shoppingcart@0.1.0~start: Failed to exec start script
13 verbose stack Error: kraken-example-with-shoppingcart@0.1.0 start: `grunt build && node index.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:887:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid kraken-example-with-shoppingcart@0.1.0
15 verbose cwd /home/abhinavralhan/kraken-example-with-shoppingcart
16 verbose Linux 3.19.0-84-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.0.0
19 verbose npm  v5.0.3
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error kraken-example-with-shoppingcart@0.1.0 start: `grunt build && node index.js`
24 error spawn ENOENT
25 error Failed at the kraken-example-with-shoppingcart@0.1.0 start script.
25 error This is probably not a problem with npm. There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by grawk** [comment]
Have you tried with node 4 or node 6? We haven't tested this on node 8 yet so that might be the issue

**Comment by abhinavralhan** [comment]
Oh, okay. Do I have to downgrade from Node 8 to Node 4 for this or is these any other way around it ?
Could you also suggest me some alternate for Krakenjs, in case it exists and it's in your knowledge.

**Comment by grawk** [comment]
as mentioned above, try node 6.. I'll take it as an action item to try with node 8.

**Comment by mylastore** [comment]
Also won't run with node 7.2.1 --- well it did run with node v 7.2.1 using this command node **index.js** instead of the one suggested on the documentation.  :)

**Comment by grawk** [comment]
works with node v8/npm v5. Need more info about the failure for you. Can you provide OS version as well? In general, we are probably going to move away from this react pattern (anemone) in favor of what we use internally.
